# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_action_controller:
      type: position_controllers/GripperActionController

joint_trajectory_controller:
  ros__parameters:
    joints: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      goal_time: 0.0

gripper_action_controller:
  ros__parameters:
    action_monitor_rate: 20.0 # Hz
    joint: robotiq_hande_left_finger_joint
    max_effort: 10.0 # N
    goal_tolerance: 0.01 # m
    allow_stalling: false
    stall_velocity_threshold: 0.001 #m/s
    stall_timeout: 1.0 # s
    state_interfaces:
      - position
