motion_server_node:
  ros__parameters:
    move_group_name: "arm_right_torso"
    end_effector_name: "gripper_right_base_link"
    base_link_name: "base_footprint"
    joint_names:
      - 'torso_lift_joint'
      - 'arm_right_1_joint'
      - 'arm_right_2_joint'
      - 'arm_right_3_joint'
      - 'arm_right_4_joint'
      - 'arm_right_5_joint'
      - 'arm_right_6_joint'
      - 'arm_right_7_joint'

    cartesian_max_step: 0.001
    cartesian_fraction_threshold: 0.9
    cartesian_jump_threshold: 0.0
    cartesian_avoid_collisions: True
    max_velocity: 0.4
    max_acceleration: 0.4
    planner_id: RRTConnectkConfigDefault
    allowed_planning_time: 8.0
    virtual_end_effector: "tip"
