table_scene_publisher_node:
  ros__parameters:
    table_length: 1.5
    table_width: 1.0
    table_thickness: 0.05
    leg_thickness: 0.05
    leg_height: 0.74
    table_pos_x: 1.1
    table_pos_y: 0.0
    table_pos_z: 0.0

static_tip_frame_publisher_node:
  ros__parameters:
    tip_z: 0.15
