<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="platform">

   <!-- Declare 'world' -->
   <link name="world"/>

   <!-- Table parameters -->
   <xacro:property name="table_length" value="1.2"/>
   <xacro:property name="table_width" value="0.6"/>
   <xacro:property name="table_height" value="0.75"/>
   <xacro:property name="table_thickness" value="0.05"/>
   <xacro:property name="leg_width" value="0.05"/>

   <link name="table_top">
      <visual>
         <geometry>
            <box size="${table_length} ${table_width} ${table_thickness}"/>
         </geometry>
         <origin xyz="0 0 -${table_thickness/2}" rpy="0 0 0"/>
         <material name="brown">
            <color rgba="0.4 0.2 0 1"/>
         </material>
      </visual>
      <collision>
         <geometry>
            <box size="${table_length} ${table_width} ${table_thickness}"/>
         </geometry>
         <origin xyz="0 0 -${table_thickness/2}" rpy="0 0 0"/>
         <material name="brown">
            <color rgba="0.4 0.2 0 1"/>
         </material>
      </collision>
   </link>

   <joint name="world_to_table" type="fixed">
      <parent link="world"/>
      <child link="table_top"/>
      <origin xyz="0 0 ${table_height}" rpy="0 0 0"/>
   </joint>

   <xacro:macro name="table_leg" params="name x y z">
      <link name="${name}">
         <visual>
            <geometry>
               <box size="${leg_width} ${leg_width} ${z}"/>
            </geometry>
            <origin xyz="0 0 ${z / 2}" rpy="0 0 0"/>
            <material name="black">
               <color rgba="0.1 0.1 0.1 1"/>
            </material>
         </visual>
         <collision>
            <geometry>
               <box size="${leg_width} ${leg_width} ${z}"/>
            </geometry>
            <origin xyz="0 0 ${z / 2}" rpy="0 0 0"/>
            <material name="black">
               <color rgba="0.1 0.1 0.1 1"/>
            </material>
      </collision>
      </link>
      <joint name="joint_${name}" type="fixed">
         <parent link="world"/>
         <child link="${name}"/>
         <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
         </joint>
   </xacro:macro>

   <xacro:table_leg name="leg_1" x="${table_length / 2 - leg_width / 2}" y="${table_width / 2 - leg_width / 2}" z="${table_height - table_thickness}"/>
   <xacro:table_leg name="leg_2" x="${-table_length / 2 + leg_width / 2}" y="${table_width / 2 - leg_width / 2}" z="${table_height - table_thickness}"/>
   <xacro:table_leg name="leg_3" x="${table_length / 2 - leg_width / 2}" y="${-table_width / 2 + leg_width / 2}" z="${table_height - table_thickness}"/>
   <xacro:table_leg name="leg_4" x="${-table_length / 2 + leg_width / 2}" y="${-table_width / 2 + leg_width / 2}" z="${table_height - table_thickness}"/>

   <!-- Virtual safety barriers (collision walls) -->
   <xacro:macro name="safety_barrier" params="name xyz size">
   <link name="${name}">
      <visual>
         <geometry>
         <box size="${size}"/>
         </geometry>
         <origin xyz="${xyz}" rpy="0 0 0"/>
         <material name="red_transparent">
         <color rgba="1.0 1.0 0.5 0.3"/>
         </material>
      </visual>
      <collision>
         <geometry>
         <box size="${size}"/>
         </geometry>
         <origin xyz="${xyz}" rpy="0 0 0"/>
      </collision>
   </link>
   <joint name="joint_${name}" type="fixed">
      <parent link="table_top"/>
      <child link="${name}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
   </joint>
   </xacro:macro>

   <!-- Barrier behind the robot -->
   <xacro:safety_barrier name="barrier_back"
   xyz="${-table_length/2 - 0.1} 0 0.3"
   size="0.01 ${table_width} 0.8"/>

   <!-- Barrier to the left -->
   <xacro:safety_barrier name="barrier_left"
   xyz="0 ${-table_width/2 - 0.1} 0.3"
   size="${table_length} 0.01 0.8"/>

   <!-- Barrier to the right -->
   <xacro:safety_barrier name="barrier_right"
   xyz="0 ${table_width/2 + 0.1} 0.3"
   size="${table_length} 0.01 0.8"/>

   <!-- Barrier above -->
   <xacro:safety_barrier name="barrier_top"
   xyz="0 0 0.8"
   size="${table_length} ${table_width} 0.01"/>

   <!-- Yumi arm -->
  <xacro:arg name="use_fake_hardware" default="true"/>
  <xacro:property name="use_fake_hardware" value="$(arg use_fake_hardware)"/>
  <xacro:arg name="rws_ip" default="192.168.125.1"/>
  <xacro:property name="rws_ip" value="$(arg rws_ip)"/>
  <xacro:arg name="rws_port" default="443"/>
  <xacro:property name="rws_port" value="$(arg rws_port)"/>
  <xacro:arg name="configure_via_rws" default="false"/>
  <xacro:property name="configure_via_rws" value="$(arg configure_via_rws)"/>

  <!-- Robot description -->
  <xacro:include filename="$(find yumi_single_arm_support)/urdf/yumi_single_arm_macro.xacro"/>
  <xacro:yumi_single_arm prefix=""/>

  <!-- Gripper description -->
  <xacro:include filename="$(find yumi_single_arm_support)/urdf/yumi_gripper_macro.xacro"/>
  <xacro:yumi_gripper prefix=""/>

  <joint type="fixed" name="flange_to_gripper">
    <parent link="flange" />
    <child link="gripper_base" />
    <origin xyz="0 0 0.007" rpy="0 0 ${radians(180)}" />
  </joint>
   
  <link name="tip"/>

  <joint type="fixed" name="grasp_link_to_tip">
    <parent link="grasp_link" />
    <child link="tip" />
    <origin xyz="0 0 -0.015" rpy="0 0 0" />
  </joint>

  <!-- ros2_control -->
  <xacro:include filename="$(find yumi_single_arm_support)/urdf/yumi_single_arm.ros2_control.xacro" />
  <xacro:abb_ros2_control
    name="ABBMultiInterfaceHardware"
    prefix=""
    use_fake_hardware="${use_fake_hardware}"
    rws_ip="${rws_ip}"
    rws_port="${rws_port}"
    configure_via_rws="${configure_via_rws}"/>

  <!-- ros2_control gripper -->
  <xacro:if value="${use_fake_hardware}">
    <xacro:include filename="$(find yumi_single_arm_support)/urdf/yumi_gripper.ros2_control.xacro" />
    <xacro:yumi_gripper_ros2_control
      name="GripperInterfaceHardware"
      prefix=""
      use_fake_hardware="${use_fake_hardware}"/>
  </xacro:if>  

   <joint name="table_top_to_base_link" type="fixed">
      <parent link="table_top"/>
      <child link="base_link"/>
      <origin xyz="${-table_length/2.0 + 0.1} 0 0" rpy="0 0 0"/>
   </joint>

</robot>