# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    open_loop_control: true
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
    # gains are used only if open_loop_control is set to false
    gains:
      joint_1:
        ff_velocity_scale: 1.0
        p: 5.0
        d: 0.0
        i: 0.0
      joint_2:
        ff_velocity_scale: 1.0
        p: 5.0
        d: 0.0
        i: 0.0
      joint_3:
        ff_velocity_scale: 1.0
        p: 5.0
        d: 0.0
        i: 0.0
      joint_4:
        ff_velocity_scale: 1.0
        p: 5.0
        d: 0.0
        i: 0.0
      joint_5:
        ff_velocity_scale: 1.0
        p: 5.0
        d: 0.0
        i: 0.0
      joint_6:
        ff_velocity_scale: 1.0
        p: 5.0
        d: 0.0
        i: 0.0
      joint_7:
        ff_velocity_scale: 1.0
        p: 5.0
        d: 0.0
        i: 0.0