motion_server_node:
  ros__parameters:
    move_group_name: "manipulator"
    end_effector_name: "tip"
    base_link_name: "base_link"
    joint_names:
      - 'joint_1'
      - 'joint_2'
      - 'joint_3'
      - 'joint_4'
      - 'joint_5'
      - 'joint_6'
      - 'joint_7'

    cartesian_max_step: 0.0025
    cartesian_fraction_threshold: 0.0
    cartesian_jump_threshold: 0.0
    cartesian_avoid_collisions: True
    max_velocity: 0.5
    max_acceleration: 0.5